name: syswatch_admin
description: Syswatch Staff, Super Admin, ITSO, and Teacher intranet application.
publish_to: 'none'
version: 2.8.0+9

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  desktop_drop: any
  file_selector: any
  path_provider: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
