name: syswatch_admin
description: SysWatch Admin intranet management application.
publish_to: 'none'
version: 2.6.0+8

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
